# Generated by Django 5.1.7 on 2025-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_item_type_comment_product_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_items',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
